#!/usr/bin/env bash
# release.sh — build a universal, signed, distributable ZAI Bar .app and ship
# it via GitHub Releases. This is the single build/release script for the
# project. (There used to be a make-app.sh; it produced an arm64-only app, so
# it was removed.)
#
# Usage:
#   ./release.sh                 # build universal, sign (adhoc unless a Developer
#                                # ID + notarytool creds are present), zip, and
#                                # print the release command
#   ./release.sh --publish       # also: tag vX.Y.Z, push it, create the GitHub Release
#   VERSION=1.2.3 ./release.sh   # override the version for this build
#
# Signing strategy (auto-detected):
#   - "Developer ID Application: ..." + APPLE_ID/APPLE_APP_SPECIFIC_PASSWORD/APPLE_TEAM_ID
#       -> hardened-runtime sign, notarize, staple
#   - otherwise
#       -> adhoc (codesign -s -); needs a one-time Gatekeeper bypass on other Macs
set -euo pipefail
cd "$(dirname "$0")"

APP_NAME="ZAIBar"
EXEC_NAME="ZAIBar"
TARGET="zai-bar"
NAME="ZAI Bar"
BUNDLE_ID="com.github.ruhex.zai-bar"
DEFAULT_VERSION="1.0.0"
VERSION="${VERSION:-$DEFAULT_VERSION}"

# 1. Stamp BuildInfo.swift from git (version, short commit, commit date, remote).
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo dev)"
CDATE="$(git log -1 --format=%cd --date=short 2>/dev/null || echo "")"
REMOTE="$(git remote get-url origin 2>/dev/null || echo "")"
if [[ "$REMOTE" == git@* ]]; then REMOTE="${REMOTE#git@}"; REMOTE="${REMOTE/://}"; fi
REMOTE="${REMOTE%.git}"
if [[ -n "$REMOTE" && "$REMOTE" != https://* && "$REMOTE" != http://* ]]; then REMOTE="https://$REMOTE"; fi
[[ -z "$REMOTE" ]] && REPO_LIT="nil" || REPO_LIT="\"$REMOTE\""

cat > "Sources/${TARGET}/BuildInfo.swift" <<EOF
// AUTO-GENERATED by release.sh — do not edit by hand.
enum BuildInfo {
    static let name = "${NAME}"
    static let version = "${VERSION}"
    static let commit = "${COMMIT}"
    static let commitDate = "${CDATE}"
    static let repoURL: String? = ${REPO_LIT}
}
EOF
echo ">> stamp: version=${VERSION} commit=${COMMIT} date=${CDATE:-<none>} repo=${REMOTE:-<none>}"

# 2. Detect signing strategy.
DEV_ID="$(security find-identity -p codesigning -v 2>/dev/null | grep -oE '"Developer ID Application: [^"]+"' || true)"
DEV_ID="${DEV_ID#\"}"; DEV_ID="${DEV_ID%\"}"
if [[ -n "$DEV_ID" && -n "${APPLE_ID:-}" && -n "${APPLE_APP_SPECIFIC_PASSWORD:-}" && -n "${APPLE_TEAM_ID:-}" ]]; then
  STRATEGY="notarized"
  echo ">> signing: Developer ID + notarize ($DEV_ID)"
else
  STRATEGY="adhoc"
  DEV_ID="-"
  echo ">> signing: adhoc (-) — no Developer ID / notarytool credentials found."
  echo "   Other Macs will need a one-time Gatekeeper bypass:"
  echo "     xattr -dr com.apple.quarantine /Applications/ZAIBar.app"
fi

# 3. Universal build. NOTE: the universal product lives under
#    .build/apple/Products/Release/ — .build/release/ is single-arch (arm64)!
echo ">> swift build -c release --arch arm64 --arch x86_64"
swift build -c release --arch arm64 --arch x86_64
UNIVERSAL_BIN=".build/apple/Products/Release/${TARGET}"
[[ -f "$UNIVERSAL_BIN" ]] || { echo "!! universal binary not found at $UNIVERSAL_BIN" >&2; exit 1; }
echo ">> file: $(file -b "$UNIVERSAL_BIN")"

# 4. Assemble the .app bundle.
OUT=".build/${APP_NAME}.app"
rm -rf "$OUT"
mkdir -p "$OUT/Contents/MacOS"
cp "$UNIVERSAL_BIN" "$OUT/Contents/MacOS/${EXEC_NAME}"
chmod +x "$OUT/Contents/MacOS/${EXEC_NAME}"
cat > "$OUT/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${NAME}</string>
  <key>CFBundleDisplayName</key><string>${NAME}</string>
  <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundleShortVersionString</key><string>${VERSION}</string>
  <key>CFBundleExecutable</key><string>${EXEC_NAME}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>14.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
EOF

# 5. Sign the bundle.
if [[ "$STRATEGY" == "notarized" ]]; then
  echo ">> codesign (Developer ID, hardened runtime)"
  codesign --force --deep --options runtime --timestamp --sign "$DEV_ID" "$OUT"
else
  echo ">> codesign (adhoc)"
  codesign --force --deep --sign - "$OUT"
fi
codesign --verify --verbose=2 "$OUT" || true

# 6. Zip with ditto (plain zip breaks the bundle layout / Gatekeeper).
ZIP=".build/${TARGET}-${VERSION}-universal-macos.zip"
rm -f "$ZIP"
ditto -c -k --keepParent "$OUT" "$ZIP"
echo "✓ Packaged: $ZIP ($(du -h "$ZIP" | cut -f1))"

# 7. Notarize + staple (only when fully provisioned). notarytool submits a zip,
#    then we staple the .app and re-zip so the download carries the ticket.
if [[ "$STRATEGY" == "notarized" ]]; then
  echo ">> notarytool submit"
  xcrun notarytool submit "$ZIP" \
    --apple-id "$APPLE_ID" \
    --password "$APPLE_APP_SPECIFIC_PASSWORD" \
    --team-id "$APPLE_TEAM_ID" --wait
  xcrun stapler staple "$OUT"
  xcrun stapler validate "$OUT"
  rm -f "$ZIP"
  ditto -c -k --keepParent "$OUT" "$ZIP"
fi

# 8. Release notes (adhoc builds always include the Gatekeeper bypass note).
NOTES=".build/release-notes-${VERSION}.md"
cat > "$NOTES" <<EOF
# ZAI Bar ${VERSION}

Universal macOS app (Apple Silicon + Intel). Requires macOS 14.0+.

## Install
Download and unzip \`${TARGET}-${VERSION}-universal-macos.zip\`, then drag
**ZAIBar.app** to /Applications and launch it. Click the ⚡ icon and paste your
z.ai API key.

EOF
if [[ "$STRATEGY" != "notarized" ]]; then
cat >> "$NOTES" <<'EOF'
> This build is adhoc-signed (not notarized). The first time you open it,
> Gatekeeper will block it. Bypass once:
>
> ```bash
> xattr -dr com.apple.quarantine /Applications/ZAIBar.app
> ```
>
> or right-click the app → **Open** → **Open anyway**.
EOF
fi

# 9. Publish (optional).
GH_CMD="gh release create v${VERSION} \"${ZIP}\" --title \"${APP_NAME} ${VERSION}\" --notes-file \"${NOTES}\""
echo ""
echo "To publish:  ${GH_CMD}"
if [[ "${1:-}" == "--publish" ]]; then
  git tag "v${VERSION}"
  git push origin "v${VERSION}"
  eval "$GH_CMD"
else
  echo "(pass --publish to tag v${VERSION} and create the release)"
fi
