// AUTO-GENERATED by release.sh — do not edit by hand.
// Defaults shown for `swift run` (no git info available); release.sh regenerates
// this on release builds with the real version, commit, date, and repo URL.
enum BuildInfo {
    static let name = "ZAI Bar"
    static let version = "1.0.0"
    static let commit = "dev"
    static let commitDate = ""
    static let repoURL: String? = nil
}
